### ISSUE TITLE
Data for table view does not work correctly with multiple capabilities

### ISSUE THREAD

**Issue by longpt214** [forward-uiuc/Web-Data-View#42]
Open Staple.com search for laptop. Click on an Operating system. 

First filter by left align, then filter by prefix. Then export to table. Then you will see some data values should not be there in the table.

**Comment by herbherbherb** [comment]
I tried, and noticed that filter by left align + prefix is not the optimal approach as it does not actually select the desired element, and therefore, the data export to csv is not desirable. Try select just use className might be better.

**Comment by longpt214** [comment]
This is just an example. The issue is the behavior is incorrect. The desired elements are subjective. What if the users actually want the left align + prefix.  Anyway, my point is when using multiple capabilities, the behavior seems to be incorrect as I explained above. @herbherbherb

**Comment by herbherbherb** [comment]
When the user decide to use left align + prefix, I print out the element that is highlighted and it is the data that is export to CSV. So i do not think there is anything wrong with the outputting to csv part or keeping tack of the selected data.
I did not implement prefix so I would have to take a look later,  maybe the filter is wrong and cause the problem?

**Comment by longpt214** [comment]
You can see that the redundant data appear in the records where there is no Operating System. So I guess when the users use prefix filter, which makes the number of selected elements smaller, the fields for the records that do not contain elements satisfying new filters are still filled with elements in the previous filter (left align). Does it make sense?

**Comment by herbherbherb** [comment]
I am not sure, I will take a look later

**Comment by jrxk** [comment]
From `tooltip.js`:
```
        function helper(referenceElement, cur_query, flag_val){
            if(flag_val === 0){
                tooltip_color = "rgb" + COLORS[class_to_color_idx[referenceElement.className]]; // classname to color
                cur_query.highlightSelectedElements(tooltip_color);
                field_label = ntc.name(rgb2hex(tooltip_color))[1]; //any color -> close name to it
                fieldname_color[field_label] = tooltip_color;
                let dom_elements = cur_query.execute();
                let data_to_push = null;
                for(let i = 0; i < dom_elements.length; i++){
                    data_to_push = {};  //dic label name ->
                    data_to_push[field_label] = dom_elements[i];
                    collected_data.push(data_to_push);
                }
            }
            else{
                cur_query.highlightSelectedElements(tooltip_color);
                let new_collect = [];
                let target_class = referenceElement.className;
                for (let j=0; j < collected_data.length; j++) {
                    let kval = Object.values(collected_data[j])[0];
                    if(kval.className !== target_class){
                        new_collect.push(collected_data[j]);
                    }
                }
                collected_data = new_collect;
            }
        }
```
This function is called each time we click on a filter. Now, it looks like we are not further filtering the data in `collected_data`, but pushing new filtered data to it. Which means there would be redundant old values.

**Comment by jrxk** [comment]
Fixed the redundant values by removing the column of data with corresponding label before pushing new data.
